---
title: "README"
output: github_document
---

`data/`

-   dataset as csv

-   data dictionary as csv

Code Description

`code/01_data_clean.R`git init

-   loads and cleans data

-   adds labels

-   saves cleaned dataset as a .rds object (`clean_data.rds`) in `data/` folder

`code/02_make_visuals`

-   reads in cleaned data

-   makes figures and saves in the `output/` folder

    -   `fig_intubation_by_age.png`

    -   `fig_intubation_by_sex.png`

    -   `fig_intubation_by_comorbidity.png`

`code/03_regression.R`

-   creates a logistic regression model for each of the outcome variables

-   saves the results as an rds object (`table_regression_results.rds`) in the `output` folder

`code/render_report.R`

-   renders report.Rmd

`report.Rmd`

-   reads cleaned data created by code/data_clean.R

-   creates a descriptive table

-   reads in contents of the `results/` folder

`Makefile`

-   can be used to render the contents of the code/ folder, including rendering the report

-   can remove .rds, .png, and .html files using the clean command
